
language: php

php:
  - 7.0

sudo: required

before_install:
  - curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | sudo bash

install:
  - sudo apt-get install php7.0-phalcon

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)