
language: php

php:
  - 7.0

sudo: required

install:
  - sudo apt-get install php7.0-dev
  - cd /tmp
  - git clone https://github.com/phalcon/cphalcon.git
  - cd cphalcon/build
  - sudo ./install
  - echo "extension=phalcon.so" > /etc/php/7.0/cli/conf.d/25-phalcon.ini
  - sudo service apache2 restart

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)