
language: php

php:
  - 7.0

sudo: required
dist: trusty

install:
  - sudo LC_ALL=en_US.UTF-8 add-apt-repository -y ppa:ondrej/php
  - curl -s "https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh" | sudo bash
  - sudo apt-get install php7.0-phalcon
  - sudo tail /usr/share/php7.0-phalcon/phalcon/phalcon.ini
  - ls /usr/lib/php
  - ls /usr/lib/php/20151012
  - ls /usr/lib/php/7.0
  - ls /usr/lib/php/php-helper
  - php -i

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)