
language: php

php:
  - 7.0

sudo: required
dist: trusty

cache:
  directories:
    - vendor
    - ~/.composer/cache
    - ~/cphalcon

before_install:
  - composer install --prefer-source --no-interaction
  - ls vendor
  - ls vendor/bin
  - vendor/bin/install-phalcon.sh 3.0.x

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)