
language: php

php:
  - 7.0

addons:
  apt:
    packages:
      - php7.0-phalcon

before_install:
  - https://packagecloud.io/install/repositories/phalcon/stable/script.deb.sh

before_script:
  - composer install

script:
  - phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)